# Generated by Django 2.0.1 on 2018-01-20 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('spotify_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dislikeship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='date begun')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Likeship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='date begun')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disliked', models.ManyToManyField(related_name='dislikers', through='artists.Dislikeship', to='artists.Artist')),
                ('liked', models.ManyToManyField(related_name='likers', through='artists.Likeship', to='artists.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='likeship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.User'),
        ),
        migrations.AddField(
            model_name='dislikeship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.User'),
        ),
    ]
