# Generated by Django 2.0.1 on 2018-01-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_id',
            field=models.CharField(default='', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='disliked',
            field=models.ManyToManyField(blank=True, related_name='dislikers', through='artists.Dislikeship', to='artists.Artist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likers', through='artists.Likeship', to='artists.Artist'),
        ),
    ]
